package biubiu.Service;

import biubiu.Model.Advertising_seat;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

public interface Advertising_seatService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_seat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_seat
     *
     * @mbggenerated
     */
    int insert(Advertising_seat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_seat
     *
     * @mbggenerated
     */
    int insertSelective(Advertising_seat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_seat
     *
     * @mbggenerated
     */
    Advertising_seat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_seat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Advertising_seat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising_seat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Advertising_seat record);
    List<Advertising_seat> selectAll();
    void updateByFirmId(String firmid);
}