package biubiu.Service;

import biubiu.Model.Job_seeker;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


public interface Job_seekerService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_seeker
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_seeker
     *
     * @mbggenerated
     */
    int insert(Job_seeker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_seeker
     *
     * @mbggenerated
     */
    int insertSelective(Job_seeker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_seeker
     *
     * @mbggenerated
     */
    Job_seeker selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_seeker
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Job_seeker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_seeker
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Job_seeker record);
    List<Job_seeker> selectAll();
}