package biubiu.Service;

import biubiu.Model.Recruit_area;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;


public interface Recruit_areaService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_area
     *
     * @mbggenerated
     */
    int insert(Recruit_area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_area
     *
     * @mbggenerated
     */
    int insertSelective(Recruit_area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_area
     *
     * @mbggenerated
     */
    Recruit_area selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Recruit_area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Recruit_area record);
    List<Recruit_area> selectAll();
}