package biubiu.Model;

import java.io.Serializable;

public class Advertising_seat implements Serializable {
    public Advertising_seat(Integer id, String advertisingSeatNum, String firmId, Integer remainTime, Integer price, String state) {
        this.id = id;
        this.advertisingSeatNum = advertisingSeatNum;
        this.firmId = firmId;
        this.remainTime = remainTime;
        this.price = price;
        this.state = state;
    }

    public Advertising_seat(String advertisingSeatNum, Integer remainTime, Integer price, String state) {
        this.advertisingSeatNum = advertisingSeatNum;
        this.remainTime = remainTime;
        this.price = price;
        this.state = state;
    }

    public Advertising_seat(String advertisingSeatNum, String firmId, Integer remainTime, Integer price, String state) {
        this.advertisingSeatNum = advertisingSeatNum;
        this.firmId = firmId;
        this.remainTime = remainTime;
        this.price = price;
        this.state = state;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_seat.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_seat.advertising_seat_num
     *
     * @mbggenerated
     */
    private String advertisingSeatNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_seat.firm_id
     *
     * @mbggenerated
     */
    private String firmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_seat.remain_time
     *
     * @mbggenerated
     */
    private Integer remainTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_seat.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising_seat.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_seat.id
     *
     * @return the value of advertising_seat.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_seat.id
     *
     * @param id the value for advertising_seat.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_seat.advertising_seat_num
     *
     * @return the value of advertising_seat.advertising_seat_num
     *
     * @mbggenerated
     */
    public String getAdvertisingSeatNum() {
        return advertisingSeatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_seat.advertising_seat_num
     *
     * @param advertisingSeatNum the value for advertising_seat.advertising_seat_num
     *
     * @mbggenerated
     */
    public void setAdvertisingSeatNum(String advertisingSeatNum) {
        this.advertisingSeatNum = advertisingSeatNum == null ? null : advertisingSeatNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_seat.firm_id
     *
     * @return the value of advertising_seat.firm_id
     *
     * @mbggenerated
     */
    public String getFirmId() {
        return firmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_seat.firm_id
     *
     * @param firmId the value for advertising_seat.firm_id
     *
     * @mbggenerated
     */
    public void setFirmId(String firmId) {
        this.firmId = firmId == null ? null : firmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_seat.remain_time
     *
     * @return the value of advertising_seat.remain_time
     *
     * @mbggenerated
     */
    public Integer getRemainTime() {
        return remainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_seat.remain_time
     *
     * @param remainTime the value for advertising_seat.remain_time
     *
     * @mbggenerated
     */
    public void setRemainTime(Integer remainTime) {
        this.remainTime = remainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_seat.price
     *
     * @return the value of advertising_seat.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_seat.price
     *
     * @param price the value for advertising_seat.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising_seat.state
     *
     * @return the value of advertising_seat.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising_seat.state
     *
     * @param state the value for advertising_seat.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}