package biubiu.Model;

import java.io.Serializable;

public class Job_seeker implements Serializable {
    public Job_seeker(Integer id, String name, String phone, Integer jobPurpose) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.jobPurpose = jobPurpose;
    }

    public Job_seeker(String name, String phone, Integer jobPurpose) {
        this.name = name;
        this.phone = phone;
        this.jobPurpose = jobPurpose;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_seeker.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_seeker.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_seeker.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_seeker.job_purpose
     *
     * @mbggenerated
     */
    private Integer jobPurpose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_seeker.id
     *
     * @return the value of job_seeker.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_seeker.id
     *
     * @param id the value for job_seeker.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_seeker.name
     *
     * @return the value of job_seeker.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_seeker.name
     *
     * @param name the value for job_seeker.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_seeker.phone
     *
     * @return the value of job_seeker.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_seeker.phone
     *
     * @param phone the value for job_seeker.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_seeker.job_purpose
     *
     * @return the value of job_seeker.job_purpose
     *
     * @mbggenerated
     */
    public Integer getJobPurpose() {
        return jobPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_seeker.job_purpose
     *
     * @param jobPurpose the value for job_seeker.job_purpose
     *
     * @mbggenerated
     */
    public void setJobPurpose(Integer jobPurpose) {
        this.jobPurpose = jobPurpose;
    }
}