package biubiu.Model;

import java.io.Serializable;

public class Participate_firm implements Serializable {
    public Participate_firm(Integer id, Integer firmId, Integer recruitFairId) {
        this.id = id;
        this.firmId = firmId;
        this.recruitFairId = recruitFairId;
    }

    public Participate_firm(Integer firmId, Integer recruitFairId) {
        this.firmId = firmId;
        this.recruitFairId = recruitFairId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participate_firm.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participate_firm.firm_id
     *
     * @mbggenerated
     */
    private Integer firmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participate_firm.recruit_fair_id
     *
     * @mbggenerated
     */
    private Integer recruitFairId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participate_firm.id
     *
     * @return the value of participate_firm.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participate_firm.id
     *
     * @param id the value for participate_firm.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participate_firm.firm_id
     *
     * @return the value of participate_firm.firm_id
     *
     * @mbggenerated
     */
    public Integer getFirmId() {
        return firmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participate_firm.firm_id
     *
     * @param firmId the value for participate_firm.firm_id
     *
     * @mbggenerated
     */
    public void setFirmId(Integer firmId) {
        this.firmId = firmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participate_firm.recruit_fair_id
     *
     * @return the value of participate_firm.recruit_fair_id
     *
     * @mbggenerated
     */
    public Integer getRecruitFairId() {
        return recruitFairId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participate_firm.recruit_fair_id
     *
     * @param recruitFairId the value for participate_firm.recruit_fair_id
     *
     * @mbggenerated
     */
    public void setRecruitFairId(Integer recruitFairId) {
        this.recruitFairId = recruitFairId;
    }
}