package biubiu.Model;

import java.io.Serializable;

public class Recruit_fair implements Serializable {
    public Recruit_fair(Integer id, String name, String time) {
        this.id = id;
        this.name = name;
        this.time = time;
    }

    public Recruit_fair(String name, String time) {
        this.name = name;
        this.time = time;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_fair.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_fair.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_fair.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_fair.id
     *
     * @return the value of recruit_fair.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_fair.id
     *
     * @param id the value for recruit_fair.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_fair.name
     *
     * @return the value of recruit_fair.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_fair.name
     *
     * @param name the value for recruit_fair.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_fair.time
     *
     * @return the value of recruit_fair.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_fair.time
     *
     * @param time the value for recruit_fair.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}