package biubiu.Dao;

import biubiu.Model.Recruit_seat;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface Recruit_seatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_seat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_seat
     *
     * @mbggenerated
     */
    int insert(Recruit_seat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_seat
     *
     * @mbggenerated
     */
    int insertSelective(Recruit_seat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_seat
     *
     * @mbggenerated
     */
    Recruit_seat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_seat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Recruit_seat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_seat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Recruit_seat record);
    List<Recruit_seat> selectAll();
    List<Recruit_seat> selectByAreaId(Integer recruit_area_id);
    void updateByFirmId(@Param("firmid") String firmid);
}